### ISSUE TITLE
Roadmap Template

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/FairChange#48]
### Background on the problem the feature will solve/improved user experience
Add GitHub Actions to test and build new code pushed to a branch or committed to a pull request. Code that passes all the steps in the GitHub action can be merged in the repository.

### Describe the solution you'd like
A GitHub action runs whenever code is committed to any branch or PR is made to the main branch for each of the following components:
- [ ] website folder
- [ ] mobile folder
- [ ] backend folder

Refer to a similar action that was implemented for the[ UI folder in Five Fifths Voter project.](https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/issues/232)

Each action will 
- [ ] install dependencies 
- [ ] build for production 
- [ ] run all tests
- [ ] linting with [prettier](https://prettier.io/docs/en/index.html). Discuss with the team on what linter to use.

### Tasks
- [ ] Ensure install, build and lint steps run locally on your system
- [ ] Read more about [GitHub actions](https://docs.github.com/en/actions/learn-github-actions) 
- [ ] Create an action for each folder. You can read more [JavaScript build actions here](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs-or-python).
- [ ] Commit and push your GitHub action code.
- [ ] Go to the [Actions tab](https://github.com/Call-for-Code-for-Racial-Justice/FairChange/actions) to see if it worked.

### Acceptance Criteria 
GitHub action runs for every new code commit and PR.

FYI @demilolu @davidnixon

**Comment by arianahl** [comment]
Hi, I would like to work on this issue

**Comment by demilolu** [comment]
@arianahl go for it!

**Comment by arianahl** [comment]
@demilolu the pull request adds the git actions requested. A few things I would like to point out:

1. backend and website don't have tests so I left that line commented out
2. backend and mobile don't have lint configured so I left that line commented out
3. website has lint but it is misconfigured and gives many errors when running

Are these known issues?

**Comment by demilolu** [comment]
@kyleni are you able to review the related PRs please?
